CREATE TABLE `v9_content_1` (
    `ContentID` int(10) NOT NULL AUTO_INCREMENT,
    `Title` varchar(250) DEFAULT NULL,
    `TitleColor` varchar(7) DEFAULT NULL,
    `Author` varchar(20) DEFAULT NULL,
    `Editor` varchar(20) DEFAULT NULL,
    `Photo` varchar(250) DEFAULT NULL,
    `SubTitle` varchar(250) DEFAULT NULL,
    `Content` longtext,
    `Keywords` varchar(250) DEFAULT NULL,
    `FromSite` varchar(250) DEFAULT NULL,
    `Intro` mediumtext,
    `CustomLinks` mediumtext,
    `CreationDate` int(10) DEFAULT '0',
    `ModifiedDate` int(10) DEFAULT '0',
    `CreationUserID` int(8) DEFAULT '0',
    `LastModifiedUserID` int(8) DEFAULT '0',
    `ContributionUserID` int(8) DEFAULT '0',
    `ContributionID` int(8) DEFAULT '0',
    `SchoolID` varchar(250) DEFAULT NULL,
    `AgentID` varchar(250) DEFAULT NULL,
    `Pic1` varchar(250) DEFAULT NULL,
    `Pic2` varchar(250) DEFAULT NULL,
    `Pic3` varchar(250) DEFAULT NULL,
    `Agent_Name` varchar(250) DEFAULT NULL,
    `School_Name` varchar(250) DEFAULT NULL,
    `guest` varchar(20) DEFAULT NULL,
    `caseinfo` varchar(250) DEFAULT NULL,
    `USAER_SchoolID` varchar(250) DEFAULT NULL,
    `USAER_School_Name` varchar(250) DEFAULT NULL,
    `education` varchar(250) DEFAULT NULL,
    `MajorKeywords` varchar(250) DEFAULT NULL,
    `generalcode` text,
    `51offer_tag` varchar(250) DEFAULT NULL,
    `51offer_tag2` varchar(250) DEFAULT NULL,
    `51offer_tag3` varchar(250) DEFAULT NULL,
    `51offer_recommend` varchar(250) DEFAULT NULL,
    `Pic4` varchar(250) DEFAULT NULL,
    `sort` varchar(250) DEFAULT NULL,
    `pic5` varchar(250) DEFAULT NULL,
    `country` varchar(250) DEFAULT NULL,
    `invalid_date` varchar(250) DEFAULT NULL,
    `point_sort` varchar(250) DEFAULT NULL,
    `pic6` varchar(250) DEFAULT NULL,
    PRIMARY KEY (`ContentID`)
) ENGINE=MyISAM AUTO_INCREMENT=143731 DEFAULT CHARSET=gbk
